[workspace]
resolver = "2"
members = [
    "crates/rustgql_common",
    "crates/rustgql_parser",
    "crates/rustgql_typegen",
    "crates/rustgql_minifier",
    "crates/rustgql_cli",
    "crates/rustgql_core",
    "crates/playground"
]